### ISSUE TITLE
FeatRequest: Storybook

### ISSUE THREAD

**Issue by aisflat439** [suren-atoyan/react-pwa#32]
I'm using this template as a reference ([helped with a typo](https://github.com/suren-atoyan/react-pwa/pull/31)). I tried to add in storybook but didn't get very far before moving on. I ran into this kind of obscure error and figured I could look into it later in the week.

```
10:50:54 AM [vite] 
Vite Error, /node_modules/.vite-storybook/deps/storybook-addon-material-ui.js?v=fdcaf5f1 optimized info should be defined
```

Have you set up storybook before with Vite and MUI? Did you have any success?

**Comment by suren-atoyan** [comment]
I've never used `vite + MUI + storybook` before 😕

**Comment by aisflat439** [comment]
If I solve are you interested in the PR? Totally okay if it's out of scope.

**Comment by suren-atoyan** [comment]
`storybook` is out of scope, but if it's related to `react-pwa` setup in general, of course, would love to have the PR
