### ISSUE TITLE
vite-plugin-pwa 2.0 and vite 3.0

### ISSUE THREAD

**Issue by AntonOfTheWoods** [suren-atoyan/react-pwa#35]
After upgrading all dependencies to their latest versions, setting `devOptions: { enabled: true, },` breaks with 

```
workbox-958fa2bd.js:1 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"http://localhost:5173/registerSW.js","status":404}]
    at C (http://localhost:5173/workbox-958fa2bd.js:1:10469)
    at async C.L (http://localhost:5173/workbox-958fa2bd.js:1:10021)
    at async C.q (http://localhost:5173/workbox-958fa2bd.js:1:9162)
```

Will the repo be updated to the most recent versions at some point?

**Comment by suren-atoyan** [comment]
> Will the repo be updated to the most recent versions at some point?

sure, I'll work on it upcoming days

**Comment by nichita-pasecinic** [comment]
Hi @suren-atoyan, is the update planned yet ?

**Comment by suren-atoyan** [comment]
@AntonOfTheWoods @nichita-pasecinic I've just published the new version - all packages are updated (it includes `Vite 3`)
