### ISSUE TITLE
npm ERR! Missing script: "https-preview"

### ISSUE THREAD

**Issue by sebababi** [suren-atoyan/react-pwa#43]
Hi,

When I run this, I get an error:

`npm run https-preview`

ERROR: 

`npm ERR! Missing script: "https-preview"`

Then I try to find about this error, and google says not too many results. Basically, nothing much.

npm --version 8.12.2

Any ideas? help? If you could just point me in the right direction

**Comment by suren-atoyan** [comment]
I've just checked the `package.json` and for some reason `serve` package is missing. If you don't have `serve` package installed in your machine (`npm i -g serve`) then `npm run https-preview` won't work (`Missing script: "https-preview"` message doesn't make sense in any case - probably it's an npm issue - I'll check this). So, the best solution for you would be installing `serve` package as a dev-dependency `npm i -D serve` - I'll fix this in the next version.

**Comment by suren-atoyan** [comment]
@sebababi let me know if this works
